trigger:
- main

resources:
- repo: self

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Terraform
  jobs:
  - job: TerraformJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseTerraform@0
      inputs:
        version: $(terraformVersion)

    - script: |
        terraform init
        terraform plan -out=tfplan
        terraform apply -auto-approve tfplan
      displayName: 'Terraform init, plan and apply'
      workingDirectory: Terraform

    - task: PowerShell@2
      displayName: 'Set Terraform Outputs as Pipeline Variables'
      workingDirectory: Terraform
      inputs:
        targetType: 'inline'
        script: |
          $outputs = terraform output -json | ConvertFrom-Json
          foreach ($key in $outputs.PSObject.Properties.Name) {
            $value = $outputs.$key.value
            # Uwaga: Zamień '.' na '_' w nazwach kluczy, jeśli są używane w wyjściach Terraform
            $sanitizedKey = $key -replace '\.', '_'
            echo "##vso[task.setvariable variable=$sanitizedKey;isOutput=true]$value"
          }
        pwsh: true


- stage: BuildAndPush
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: $(containerRegistry)
        repository: $(imageRepository)
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: |
          $(tag)

- stage: DeployToAKS
  jobs:
  - job: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '<Twoja subskrypcja Azure>'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az aks get-credentials --resource-group <TwojaGrupaZasobow> --name <TwojeAKSClusterName>
          kubectl set image deployment/<deploymentName> <containerName>=$(containerRegistry)/$(imageRepository):$(tag)
