apiVersion: apps/v1
kind: Deployment
metadata:
  name: projektzespolowy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projektzespolowy
  template:
    metadata:
      labels:
        app: projektzespolowy
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: projektzespolowy
        image: projektzespolowyacr.azurecr.io/projektzespolowy:74
        ports:
        - containerPort: 80
        env:
        - name: CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CONNECTION_STRING
        - name: CONTAINER_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: CONTAINER_NAME
